version: "3"

volumes:
    postgres_data:
        driver: local
    rabbitmq_data:
    rabbitmq_log:

networks:
    rabbitmq_net:
        driver: bridge

services:
    postgres:
        image: postgres:15-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data
        command: postgres -c wal_level=logical
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password

    rabbitmq:
        image: rabbitmq:3.12-management
        hostname: rabbitmq
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: DSrabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq/
            - rabbitmq_log:/var/log/rabbitmq/
        networks:
            - rabbitmq_net
